

import 'package:flutter/material.dart';
import 'login_view.dart';
import 'home_view.dart';
void main() {
  runApp(const FigmaToCodeApp());
}


void LoginPage() {
    print('bang bang bang');
  }

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          IndexPage(),
        ]),
      ),
    );
  }
}

class IndexPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 393,
          height: 852,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 17,
                top: 402,
                child: SizedBox(
                  width: 191,
                  height: 34,
                  child: Text(
                    'Existing User?',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 24,
                      fontFamily: 'Lexend Deca',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
               
               Positioned(
                left: 68,
                top: 415,
                child: SizedBox(
                  width: 252,
                  height: 100, // Increased height to accommodate both text and button
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center, // Center the content
                    crossAxisAlignment: CrossAxisAlignment.center, // Center horizontally
                    children: [
                      SizedBox(
                        width: 30, 
                        height: 10
                        ), // Space between text and button
                      ElevatedButton(
                        onPressed: () {
                          // Add your button action here (e.g., call a method or navigate)
                         Navigator.push(
                          context,
                          MaterialPageRoute(builder: (context) => LoginDart()),
                          );
                        },
                        style: ElevatedButton.styleFrom(
                          backgroundColor: Color(0xFF039900), // Button color
                          foregroundColor: Colors.white, // Text color
                          fixedSize: Size(450, 40)
                        ),
                        child: Text(
                          'Sign Up',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w400
                            ),
                          ),
                      ),
                    ],
                  ),
                ),
              ),

             
              Positioned(
                left: -3,
                top: 520,
                child: SizedBox(
                  width: 191,
                  height: 34,
                  child: Text(
                    'New User?',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 24,
                      fontFamily: 'Lexend Deca',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              
              Positioned(
                left: 68,
                top: 535,
                child: SizedBox(
                  width: 252,
                  height: 100, // Increased height to accommodate both text and button
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center, // Center the content
                    crossAxisAlignment: CrossAxisAlignment.center, // Center horizontally
                    children: [
                      SizedBox(
                        width: 30, 
                        height: 10
                        ), // Space between text and button
                      ElevatedButton(
                        
                        onPressed: () {
                          // Add your button action here (e.g., call a method or navigate)
                         Navigator.push(
                          context,
                          MaterialPageRoute(builder: (context) => HomePage()),
                          );
                        },
                        style: ElevatedButton.styleFrom(
                          backgroundColor: Color(0xFF039900), // Button color
                          foregroundColor: Colors.white, // Text color
                          fixedSize: Size(450, 40), //set width and height of button
                        ),
                        child: Text(
                          'Sign Up',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.w400,
                          )
                          
                          ),
                      ),
                    ],
                  ),
                ),
              ),



              Positioned(
                left: 81,
                top: 110,
                child: Container(
                  width: 214,
                  height: 214,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Image.asset("SoVest.png"),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
